[WIP] Introduce T0 evaluation
bigscience-workshop/t5x pull request #20
Opened 2021-12-14 21:43 UTC by thomasw21

2021-12-15 14:57 UTC, craffel requested changes

2021-12-15 14:57 UTC, craffel commented on bigscience/gins/task.py
> +    "super_glue_wsc.fixed_Who_or_what_is_are",
I think you are missing `super_glue_wsc.fixed_Who_is_are` - that one was included in our eval and plots. Did it not show up for you or something? If so, I wonder if it got removed.

2021-12-15 14:57 UTC, craffel commented on bigscience/gins/task.py
> +    "winogrande_winogrande_debiased_Replace",
you can remove all the debiased ones

2021-12-16 10:33 UTC, thomasw21 commented on bigscience/gins/task.py
> +    "super_glue_wsc.fixed_Who_or_what_is_are",
Ah I think this template was named like that prior to https://github.com/bigscience-workshop/promptsource/pull/487 Do you want me to revert back to a commit before when launching evaluation?

2021-12-16 20:29 UTC, craffel commented on bigscience/gins/task.py
> +    "super_glue_wsc.fixed_Who_or_what_is_are",
Looks good to me, thanks.

2021-12-16 20:30 UTC, craffel approved these changes

2021-12-17 11:51 UTC, merged